# Generated by Django 2.0.9 on 2018-11-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('p1_movement', models.CharField(max_length=10)),
                ('p2_movement', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.Game')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='game_player_name_13b648_idx'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to='game.Player'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['game'], name='game_round_game_id_e92669_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_one', 'player_two'], name='game_game_player__32e07f_idx'),
        ),
    ]
